In [208]:
import pandas as pd
from datetime import datetime, timedelta

In [209]:
pd.__version__

'3.0.6'

In [210]:
# 1. Create data frame
df = pd.DataFrame(data=[
  [1,2,3],
  [4,5,6],
  [7,8,9]
], columns=["col_1", "col_2", "col_3"])
df

   col_1  col_2  col_3
0      1      2      3
1      4      5      6
2      7      8      9

In [211]:
type(df)

pandas.DataFrame

In [212]:
data = {
  "name": ["demo_1", "demo_2", "demo_3", "demo_4"],
  "age": [10, 20, 30, 40],
  "place": ["demo_place_1", "demo_place_2", "demo_place_3", "demo_place_4"]
}

df = pd.DataFrame(data=data)
df

     name  age         place
0  demo_1   10  demo_place_1
1  demo_2   20  demo_place_2
2  demo_3   30  demo_place_3
3  demo_4   40  demo_place_4

In [213]:
df.head(2)

     name  age         place
0  demo_1   10  demo_place_1
1  demo_2   20  demo_place_2

In [214]:
df.tail(2)

     name  age         place
2  demo_3   30  demo_place_3
3  demo_4   40  demo_place_4

In [215]:
df

     name  age         place
0  demo_1   10  demo_place_1
1  demo_2   20  demo_place_2
2  demo_3   30  demo_place_3
3  demo_4   40  demo_place_4

In [216]:
df.size

12

In [217]:
df.shape

(4, 3)

In [218]:
df.columns

Index(['name', 'age', 'place'], dtype='str')

In [219]:
df.rename(columns={"name": "Name"})

     Name  age         place
0  demo_1   10  demo_place_1
1  demo_2   20  demo_place_2
2  demo_3   30  demo_place_3
3  demo_4   40  demo_place_4

In [220]:
df.rename(columns={"age": "Age"})

     name  Age         place
0  demo_1   10  demo_place_1
1  demo_2   20  demo_place_2
2  demo_3   30  demo_place_3
3  demo_4   40  demo_place_4

In [221]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   age     4 non-null      int64
 2   place   4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [222]:
df.describe()

             age
count   4.000000
mean   25.000000
std    12.909944
min    10.000000
25%    17.500000
50%    25.000000
75%    32.500000
max    40.000000

In [223]:
# Save and load data from csv
data_employees = {
  "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108],
  "Name": ["Alice", "Bob", "Charlie", "Diana", "Ethan", "Fiona", "George", "Hannah"],
  "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT", "HR"],
  "Age": [28, 34, 41, 29, 36, 45, 25, 31],
  "Salary": [75000, 62000, 95000, 81000, 58000, 105000, 72000, 68000],
  "Remote": [True, False, True, False, False, True, True, False]
}

df = pd.DataFrame(data=data_employees)

In [224]:
df

   Employee_ID     Name Department  Age  Salary  Remote
0          101    Alice         IT   28   75000    True
1          102      Bob         HR   34   62000   False
2          103  Charlie         IT   41   95000    True
3          104    Diana    Finance   29   81000   False
4          105    Ethan         HR   36   58000   False
5          106    Fiona    Finance   45  105000    True
6          107   George         IT   25   72000    True
7          108   Hannah         HR   31   68000   False

In [225]:
df.to_csv(path_or_buf="./data.csv", index=False)

In [226]:
df = pd.read_csv(filepath_or_buffer="./data.csv")

In [227]:
df

   Employee_ID     Name Department  Age  Salary  Remote
0          101    Alice         IT   28   75000    True
1          102      Bob         HR   34   62000   False
2          103  Charlie         IT   41   95000    True
3          104    Diana    Finance   29   81000   False
4          105    Ethan         HR   36   58000   False
5          106    Fiona    Finance   45  105000    True
6          107   George         IT   25   72000    True
7          108   Hannah         HR   31   68000   False

In [228]:
df[["Employee_ID", "Name", "Age"]]

   Employee_ID     Name  Age
0          101    Alice   28
1          102      Bob   34
2          103  Charlie   41
3          104    Diana   29
4          105    Ethan   36
5          106    Fiona   45
6          107   George   25
7          108   Hannah   31

In [229]:
df

   Employee_ID     Name Department  Age  Salary  Remote
0          101    Alice         IT   28   75000    True
1          102      Bob         HR   34   62000   False
2          103  Charlie         IT   41   95000    True
3          104    Diana    Finance   29   81000   False
4          105    Ethan         HR   36   58000   False
5          106    Fiona    Finance   45  105000    True
6          107   George         IT   25   72000    True
7          108   Hannah         HR   31   68000   False

In [230]:
df.loc[0]

Employee_ID      101
Name           Alice
Department        IT
Age               28
Salary         75000
Remote          True
Name: 0, dtype: object

In [231]:
df.loc[df.Employee_ID == 101]

   Employee_ID   Name Department  Age  Salary  Remote
0          101  Alice         IT   28   75000    True

In [232]:
df.loc[(df.Name == "Alice") & (df.Department == "IT")]

   Employee_ID   Name Department  Age  Salary  Remote
0          101  Alice         IT   28   75000    True

In [233]:
df.loc[(df.Name == "Alice") | (df.Department == "HR")]

   Employee_ID    Name Department  Age  Salary  Remote
0          101   Alice         IT   28   75000    True
1          102     Bob         HR   34   62000   False
4          105   Ethan         HR   36   58000   False
7          108  Hannah         HR   31   68000   False

In [234]:
df.loc[df.Salary >= 70000]

   Employee_ID     Name Department  Age  Salary  Remote
0          101    Alice         IT   28   75000    True
2          103  Charlie         IT   41   95000    True
3          104    Diana    Finance   29   81000   False
5          106    Fiona    Finance   45  105000    True
6          107   George         IT   25   72000    True

In [235]:
df.loc[df.Salary < 70000]

   Employee_ID    Name Department  Age  Salary  Remote
1          102     Bob         HR   34   62000   False
4          105   Ethan         HR   36   58000   False
7          108  Hannah         HR   31   68000   False

In [236]:
df.iloc[0]

Employee_ID      101
Name           Alice
Department        IT
Age               28
Salary         75000
Remote          True
Name: 0, dtype: object

In [237]:
df.iloc[df.Salary < 70000]

   Employee_ID    Name Department  Age  Salary  Remote
1          102     Bob         HR   34   62000   False
4          105   Ethan         HR   36   58000   False
7          108  Hannah         HR   31   68000   False

In [238]:
df.loc[:2]

   Employee_ID     Name Department  Age  Salary  Remote
0          101    Alice         IT   28   75000    True
1          102      Bob         HR   34   62000   False
2          103  Charlie         IT   41   95000    True

In [239]:
df.iloc[:2]

   Employee_ID   Name Department  Age  Salary  Remote
0          101  Alice         IT   28   75000    True
1          102    Bob         HR   34   62000   False

In [240]:
df.loc[::2]

   Employee_ID     Name Department  Age  Salary  Remote
0          101    Alice         IT   28   75000    True
2          103  Charlie         IT   41   95000    True
4          105    Ethan         HR   36   58000   False
6          107   George         IT   25   72000    True

In [241]:
df.iloc[::2]

   Employee_ID     Name Department  Age  Salary  Remote
0          101    Alice         IT   28   75000    True
2          103  Charlie         IT   41   95000    True
4          105    Ethan         HR   36   58000   False
6          107   George         IT   25   72000    True

In [242]:
df.loc[df.Age > 40]

   Employee_ID     Name Department  Age  Salary  Remote
2          103  Charlie         IT   41   95000    True
5          106    Fiona    Finance   45  105000    True

In [243]:
df.Age > 30

0    False
1     True
2     True
3    False
4     True
5     True
6    False
7     True
Name: Age, dtype: bool

In [244]:
df

   Employee_ID     Name Department  Age  Salary  Remote
0          101    Alice         IT   28   75000    True
1          102      Bob         HR   34   62000   False
2          103  Charlie         IT   41   95000    True
3          104    Diana    Finance   29   81000   False
4          105    Ethan         HR   36   58000   False
5          106    Fiona    Finance   45  105000    True
6          107   George         IT   25   72000    True
7          108   Hannah         HR   31   68000   False

In [245]:
df.where(df.Age > 40, other=None)

   Employee_ID     Name Department   Age    Salary Remote
0          NaN      NaN        NaN   NaN       NaN   None
1          NaN      NaN        NaN   NaN       NaN   None
2        103.0  Charlie         IT  41.0   95000.0   True
3          NaN      NaN        NaN   NaN       NaN   None
4          NaN      NaN        NaN   NaN       NaN   None
5        106.0    Fiona    Finance  45.0  105000.0   True
6          NaN      NaN        NaN   NaN       NaN   None
7          NaN      NaN        NaN   NaN       NaN   None

In [246]:
df[df.Age > 40]

   Employee_ID     Name Department  Age  Salary  Remote
2          103  Charlie         IT   41   95000    True
5          106    Fiona    Finance   45  105000    True

In [247]:
df

   Employee_ID     Name Department  Age  Salary  Remote
0          101    Alice         IT   28   75000    True
1          102      Bob         HR   34   62000   False
2          103  Charlie         IT   41   95000    True
3          104    Diana    Finance   29   81000   False
4          105    Ethan         HR   36   58000   False
5          106    Fiona    Finance   45  105000    True
6          107   George         IT   25   72000    True
7          108   Hannah         HR   31   68000   False

In [248]:
df["Extra_Pay"] = [item * 1000 for item in range(df.shape[0])]
df

   Employee_ID     Name Department  Age  Salary  Remote  Extra_Pay
0          101    Alice         IT   28   75000    True          0
1          102      Bob         HR   34   62000   False       1000
2          103  Charlie         IT   41   95000    True       2000
3          104    Diana    Finance   29   81000   False       3000
4          105    Ethan         HR   36   58000   False       4000
5          106    Fiona    Finance   45  105000    True       5000
6          107   George         IT   25   72000    True       6000
7          108   Hannah         HR   31   68000   False       7000

In [249]:
df['Bonus'] = df.Salary * .5
df

   Employee_ID     Name Department  Age  Salary  Remote  Extra_Pay    Bonus
0          101    Alice         IT   28   75000    True          0  37500.0
1          102      Bob         HR   34   62000   False       1000  31000.0
2          103  Charlie         IT   41   95000    True       2000  47500.0
3          104    Diana    Finance   29   81000   False       3000  40500.0
4          105    Ethan         HR   36   58000   False       4000  29000.0
5          106    Fiona    Finance   45  105000    True       5000  52500.0
6          107   George         IT   25   72000    True       6000  36000.0
7          108   Hannah         HR   31   68000   False       7000  34000.0

In [250]:
len(df), df.shape[0]

(8, 8)

In [251]:
df.loc[df.shape[0]] = [109, "Dheeraj", "IT", 27, 7000, False, 50000, 0]

In [252]:
df

   Employee_ID     Name Department  Age  Salary  Remote  Extra_Pay    Bonus
0          101    Alice         IT   28   75000    True          0  37500.0
1          102      Bob         HR   34   62000   False       1000  31000.0
2          103  Charlie         IT   41   95000    True       2000  47500.0
3          104    Diana    Finance   29   81000   False       3000  40500.0
4          105    Ethan         HR   36   58000   False       4000  29000.0
5          106    Fiona    Finance   45  105000    True       5000  52500.0
6          107   George         IT   25   72000    True       6000  36000.0
7          108   Hannah         HR   31   68000   False       7000  34000.0
8          109  Dheeraj         IT   27    7000   False      50000      0.0

In [253]:
df.loc[0, "Salary"] = 0

In [254]:
df

   Employee_ID     Name Department  Age  Salary  Remote  Extra_Pay    Bonus
0          101    Alice         IT   28       0    True          0  37500.0
1          102      Bob         HR   34   62000   False       1000  31000.0
2          103  Charlie         IT   41   95000    True       2000  47500.0
3          104    Diana    Finance   29   81000   False       3000  40500.0
4          105    Ethan         HR   36   58000   False       4000  29000.0
5          106    Fiona    Finance   45  105000    True       5000  52500.0
6          107   George         IT   25   72000    True       6000  36000.0
7          108   Hannah         HR   31   68000   False       7000  34000.0
8          109  Dheeraj         IT   27    7000   False      50000      0.0

In [255]:
df.loc[df.Name == "Dheeraj", "Salary"] = 90000

In [256]:
df

   Employee_ID     Name Department  Age  Salary  Remote  Extra_Pay    Bonus
0          101    Alice         IT   28       0    True          0  37500.0
1          102      Bob         HR   34   62000   False       1000  31000.0
2          103  Charlie         IT   41   95000    True       2000  47500.0
3          104    Diana    Finance   29   81000   False       3000  40500.0
4          105    Ethan         HR   36   58000   False       4000  29000.0
5          106    Fiona    Finance   45  105000    True       5000  52500.0
6          107   George         IT   25   72000    True       6000  36000.0
7          108   Hannah         HR   31   68000   False       7000  34000.0
8          109  Dheeraj         IT   27   90000   False      50000      0.0

In [257]:
df.drop(df[df.Name == "Dheeraj"].index)

   Employee_ID     Name Department  Age  Salary  Remote  Extra_Pay    Bonus
0          101    Alice         IT   28       0    True          0  37500.0
1          102      Bob         HR   34   62000   False       1000  31000.0
2          103  Charlie         IT   41   95000    True       2000  47500.0
3          104    Diana    Finance   29   81000   False       3000  40500.0
4          105    Ethan         HR   36   58000   False       4000  29000.0
5          106    Fiona    Finance   45  105000    True       5000  52500.0
6          107   George         IT   25   72000    True       6000  36000.0
7          108   Hannah         HR   31   68000   False       7000  34000.0

In [258]:
[item for item in df[df.Employee_ID == 108].index][0]

7

In [259]:
idx = df[(df.Name == "Bob") & (df.Department == "HR")].index
df.drop(idx)

   Employee_ID     Name Department  Age  Salary  Remote  Extra_Pay    Bonus
0          101    Alice         IT   28       0    True          0  37500.0
2          103  Charlie         IT   41   95000    True       2000  47500.0
3          104    Diana    Finance   29   81000   False       3000  40500.0
4          105    Ethan         HR   36   58000   False       4000  29000.0
5          106    Fiona    Finance   45  105000    True       5000  52500.0
6          107   George         IT   25   72000    True       6000  36000.0
7          108   Hannah         HR   31   68000   False       7000  34000.0
8          109  Dheeraj         IT   27   90000   False      50000      0.0

In [260]:
df

   Employee_ID     Name Department  Age  Salary  Remote  Extra_Pay    Bonus
0          101    Alice         IT   28       0    True          0  37500.0
1          102      Bob         HR   34   62000   False       1000  31000.0
2          103  Charlie         IT   41   95000    True       2000  47500.0
3          104    Diana    Finance   29   81000   False       3000  40500.0
4          105    Ethan         HR   36   58000   False       4000  29000.0
5          106    Fiona    Finance   45  105000    True       5000  52500.0
6          107   George         IT   25   72000    True       6000  36000.0
7          108   Hannah         HR   31   68000   False       7000  34000.0
8          109  Dheeraj         IT   27   90000   False      50000      0.0

In [261]:
df.sort_values(by="Salary")

   Employee_ID     Name Department  Age  Salary  Remote  Extra_Pay    Bonus
0          101    Alice         IT   28       0    True          0  37500.0
4          105    Ethan         HR   36   58000   False       4000  29000.0
1          102      Bob         HR   34   62000   False       1000  31000.0
7          108   Hannah         HR   31   68000   False       7000  34000.0
6          107   George         IT   25   72000    True       6000  36000.0
3          104    Diana    Finance   29   81000   False       3000  40500.0
8          109  Dheeraj         IT   27   90000   False      50000      0.0
2          103  Charlie         IT   41   95000    True       2000  47500.0
5          106    Fiona    Finance   45  105000    True       5000  52500.0

In [262]:
df.sort_values(by="Salary", ascending=False)

   Employee_ID     Name Department  Age  Salary  Remote  Extra_Pay    Bonus
5          106    Fiona    Finance   45  105000    True       5000  52500.0
2          103  Charlie         IT   41   95000    True       2000  47500.0
8          109  Dheeraj         IT   27   90000   False      50000      0.0
3          104    Diana    Finance   29   81000   False       3000  40500.0
6          107   George         IT   25   72000    True       6000  36000.0
7          108   Hannah         HR   31   68000   False       7000  34000.0
1          102      Bob         HR   34   62000   False       1000  31000.0
4          105    Ethan         HR   36   58000   False       4000  29000.0
0          101    Alice         IT   28       0    True          0  37500.0

In [263]:
df.shape[0]

9

In [264]:
now = datetime.now()
df["DOJ"] = [now + timedelta(days=idx + 1) for idx in range(df.shape[0])]

In [265]:
df

,Employee_ID,Name,Department,Age,Salary,Remote,Extra_Pay,Bonus,DOJ
0,101,Alice,IT,28,0,True,0,37500.0,2026-10-13 15:53:48.381536
1,102,Bob,HR,34,62000,False,1000,31000.0,2026-10-14 15:53:48.381536
2,103,Charlie,IT,41,95000,True,2000,47500.0,2026-10-15 15:53:48.381536
3,104,Diana,Finance,29,81000,False,3000,40500.0,2026-10-16 15:53:48.381536
4,105,Ethan,HR,36,58000,False,4000,29000.0,2026-10-17 15:53:48.381536
5,106,Fiona,Finance,45,105000,True,5000,52500.0,2026-10-18 15:53:48.381536
6,107,George,IT,25,72000,True,6000,36000.0,2026-10-19 15:53:48.381536
7,108,Hannah,HR,31,68000,False,7000,34000.0,2026-10-20 15:53:48.381536
8,109,Dheeraj,IT,27,90000,False,50000,0.0,2026-10-21 15:53:48.381536

In [266]:
df.DOJ.T

0   2026-10-13 15:53:48.381536
1   2026-10-14 15:53:48.381536
2   2026-10-15 15:53:48.381536
3   2026-10-16 15:53:48.381536
4   2026-10-17 15:53:48.381536
5   2026-10-18 15:53:48.381536
6   2026-10-19 15:53:48.381536
7   2026-10-20 15:53:48.381536
8   2026-10-21 15:53:48.381536
Name: DOJ, dtype: datetime64[us]

In [267]:
df["DOJ"] = pd.to_datetime(df["DOJ"], format="%d-%m-%Y")
df["DOJ_formatted"] = df["DOJ"].dt.strftime(date_format="%d-%m-%Y")

In [268]:
df

,Employee_ID,Name,Department,Age,Salary,Remote,Extra_Pay,Bonus,DOJ,DOJ_formatted
0,101,Alice,IT,28,0,True,0,37500.0,2026-10-13 15:53:48.381536,13-10-2026
1,102,Bob,HR,34,62000,False,1000,31000.0,2026-10-14 15:53:48.381536,14-10-2026
2,103,Charlie,IT,41,95000,True,2000,47500.0,2026-10-15 15:53:48.381536,15-10-2026
3,104,Diana,Finance,29,81000,False,3000,40500.0,2026-10-16 15:53:48.381536,16-10-2026
4,105,Ethan,HR,36,58000,False,4000,29000.0,2026-10-17 15:53:48.381536,17-10-2026
5,106,Fiona,Finance,45,105000,True,5000,52500.0,2026-10-18 15:53:48.381536,18-10-2026
6,107,George,IT,25,72000,True,6000,36000.0,2026-10-19 15:53:48.381536,19-10-2026
7,108,Hannah,HR,31,68000,False,7000,34000.0,2026-10-20 15:53:48.381536,20-10-2026
8,109,Dheeraj,IT,27,90000,False,50000,0.0,2026-10-21 15:53:48.381536,21-10-2026

In [269]:
df =  df.drop('DOJ', axis=1)

In [270]:
df

,Employee_ID,Name,Department,Age,Salary,Remote,Extra_Pay,Bonus,DOJ_formatted
0,101,Alice,IT,28,0,True,0,37500.0,13-10-2026
1,102,Bob,HR,34,62000,False,1000,31000.0,14-10-2026
2,103,Charlie,IT,41,95000,True,2000,47500.0,15-10-2026
3,104,Diana,Finance,29,81000,False,3000,40500.0,16-10-2026
4,105,Ethan,HR,36,58000,False,4000,29000.0,17-10-2026
5,106,Fiona,Finance,45,105000,True,5000,52500.0,18-10-2026
6,107,George,IT,25,72000,True,6000,36000.0,19-10-2026
7,108,Hannah,HR,31,68000,False,7000,34000.0,20-10-2026
8,109,Dheeraj,IT,27,90000,False,50000,0.0,21-10-2026

In [273]:
df["DOJ"] = pd.to_datetime(df["DOJ"], format="%d-%m-%Y")

KeyError: 'DOJ'

In [ ]:
df

,Employee_ID,Name,Department,Age,Salary,Remote,Bonus,Extra_Pay,DOJ
0,101,Alice,IT,28,0,True,37500.0,0,2026-10-12
1,102,Bob,HR,34,62000,False,31000.0,1000,2026-10-13
2,103,Charlie,IT,41,95000,True,47500.0,2000,2026-10-14
3,104,Diana,Finance,29,81000,False,40500.0,3000,2026-10-15
4,105,Ethan,HR,36,58000,False,29000.0,4000,2026-10-16
5,106,Fiona,Finance,45,105000,True,52500.0,5000,2026-10-17
6,107,George,IT,25,72000,True,36000.0,6000,2026-10-18
7,108,Hannah,HR,31,68000,False,34000.0,7000,2026-10-19
8,109,Dheeraj,IT,27,90000,False,3500.0,8000,2026-10-20

In [ ]:
df["DOJ"].transpose

<bound method IndexOpsMixin.transpose of 0   2026-10-12
1   2026-10-13
2   2026-10-14
3   2026-10-15
4   2026-10-16
5   2026-10-17
6   2026-10-18
7   2026-10-19
8   2026-10-20
Name: DOJ, dtype: datetime64[us]>

In [ ]:
df.DOJ.dt.year

0    2026
1    2026
2    2026
3    2026
4    2026
5    2026
6    2026
7    2026
8    2026
Name: DOJ, dtype: int32

In [ ]:
df.DOJ.dt.month

0    10
1    10
2    10
3    10
4    10
5    10
6    10
7    10
8    10
Name: DOJ, dtype: int32

In [ ]:
df.DOJ.dt.day

0    12
1    13
2    14
3    15
4    16
5    17
6    18
7    19
8    20
Name: DOJ, dtype: int32

In [ ]:
df.DOJ.dt.date

0    2026-10-12
1    2026-10-13
2    2026-10-14
3    2026-10-15
4    2026-10-16
5    2026-10-17
6    2026-10-18
7    2026-10-19
8    2026-10-20
Name: DOJ, dtype: object

In [ ]:
df.DOJ.dt.day_name()

0       Monday
1      Tuesday
2    Wednesday
3     Thursday
4       Friday
5     Saturday
6       Sunday
7       Monday
8      Tuesday
Name: DOJ, dtype: str

In [ ]:
df

,Employee_ID,Name,Department,Age,Salary,Remote,Extra_Pay,Bonus,DOJ_formatted
0,101,Alice,IT,28,0,True,0,37500.0,13-10-2026
1,102,Bob,HR,34,62000,False,1000,31000.0,14-10-2026
2,103,Charlie,IT,41,95000,True,2000,47500.0,15-10-2026
3,104,Diana,Finance,29,81000,False,3000,40500.0,16-10-2026
4,105,Ethan,HR,36,58000,False,4000,29000.0,17-10-2026
5,106,Fiona,Finance,45,105000,True,5000,52500.0,18-10-2026
6,107,George,IT,25,72000,True,6000,36000.0,19-10-2026
7,108,Hannah,HR,31,68000,False,7000,34000.0,20-10-2026
8,109,Dheeraj,IT,27,90000,False,50000,0.0,21-10-2026

In [ ]:
df.notnull()

,Employee_ID,Name,Department,Age,Salary,Remote,Extra_Pay,Bonus,DOJ_formatted
0,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True,True,True
8,True,True,True,True,True,True,True,True,True

In [ ]:
df.isnull()

,Employee_ID,Name,Department,Age,Salary,Remote,Extra_Pay,Bonus,DOJ_formatted
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False

In [ ]:
df["NULL"] = [None for _ in range(df.shape[0])]

In [ ]:
df

,Employee_ID,Name,Department,Age,Salary,Remote,Extra_Pay,Bonus,DOJ_formatted,NULL
0,101,Alice,IT,28,0,True,0,37500.0,13-10-2026,None
1,102,Bob,HR,34,62000,False,1000,31000.0,14-10-2026,None
2,103,Charlie,IT,41,95000,True,2000,47500.0,15-10-2026,None
3,104,Diana,Finance,29,81000,False,3000,40500.0,16-10-2026,None
4,105,Ethan,HR,36,58000,False,4000,29000.0,17-10-2026,None
5,106,Fiona,Finance,45,105000,True,5000,52500.0,18-10-2026,None
6,107,George,IT,25,72000,True,6000,36000.0,19-10-2026,None
7,108,Hannah,HR,31,68000,False,7000,34000.0,20-10-2026,None
8,109,Dheeraj,IT,27,90000,False,50000,0.0,21-10-2026,None

In [ ]:
df.isnull()

,Employee_ID,Name,Department,Age,Salary,Remote,Extra_Pay,Bonus,DOJ_formatted,NULL
0,False,False,False,False,False,False,False,False,False,True
1,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,True
5,False,False,False,False,False,False,False,False,False,True
6,False,False,False,False,False,False,False,False,False,True
7,False,False,False,False,False,False,False,False,False,True
8,False,False,False,False,False,False,False,False,False,True

In [ ]:
df.isnull().sum()

Employee_ID      0
Name             0
Department       0
Age              0
Salary           0
Remote           0
Extra_Pay        0
Bonus            0
DOJ_formatted    0
NULL             9
dtype: int64

In [ ]:
df

,Employee_ID,Name,Department,Age,Salary,Remote,Extra_Pay,Bonus,DOJ_formatted,NULL
0,101,Alice,IT,28,0,True,0,37500.0,13-10-2026,None
1,102,Bob,HR,34,62000,False,1000,31000.0,14-10-2026,None
2,103,Charlie,IT,41,95000,True,2000,47500.0,15-10-2026,None
3,104,Diana,Finance,29,81000,False,3000,40500.0,16-10-2026,None
4,105,Ethan,HR,36,58000,False,4000,29000.0,17-10-2026,None
5,106,Fiona,Finance,45,105000,True,5000,52500.0,18-10-2026,None
6,107,George,IT,25,72000,True,6000,36000.0,19-10-2026,None
7,108,Hannah,HR,31,68000,False,7000,34000.0,20-10-2026,None
8,109,Dheeraj,IT,27,90000,False,50000,0.0,21-10-2026,None

In [ ]:
df.fillna(1)

,Employee_ID,Name,Department,Age,Salary,Remote,Extra_Pay,Bonus,DOJ_formatted,NULL
0,101,Alice,IT,28,0,True,0,37500.0,13-10-2026,1
1,102,Bob,HR,34,62000,False,1000,31000.0,14-10-2026,1
2,103,Charlie,IT,41,95000,True,2000,47500.0,15-10-2026,1
3,104,Diana,Finance,29,81000,False,3000,40500.0,16-10-2026,1
4,105,Ethan,HR,36,58000,False,4000,29000.0,17-10-2026,1
5,106,Fiona,Finance,45,105000,True,5000,52500.0,18-10-2026,1
6,107,George,IT,25,72000,True,6000,36000.0,19-10-2026,1
7,108,Hannah,HR,31,68000,False,7000,34000.0,20-10-2026,1
8,109,Dheeraj,IT,27,90000,False,50000,0.0,21-10-2026,1

In [ ]:
df

,Employee_ID,Name,Department,Age,Salary,Remote,Extra_Pay,Bonus,DOJ_formatted,NULL
0,101,Alice,IT,28,0,True,0,37500.0,13-10-2026,None
1,102,Bob,HR,34,62000,False,1000,31000.0,14-10-2026,None
2,103,Charlie,IT,41,95000,True,2000,47500.0,15-10-2026,None
3,104,Diana,Finance,29,81000,False,3000,40500.0,16-10-2026,None
4,105,Ethan,HR,36,58000,False,4000,29000.0,17-10-2026,None
5,106,Fiona,Finance,45,105000,True,5000,52500.0,18-10-2026,None
6,107,George,IT,25,72000,True,6000,36000.0,19-10-2026,None
7,108,Hannah,HR,31,68000,False,7000,34000.0,20-10-2026,None
8,109,Dheeraj,IT,27,90000,False,50000,0.0,21-10-2026,None

In [ ]:
df.Name.value_counts()

Name
Alice      1
Bob        1
Charlie    1
Diana      1
Ethan      1
Fiona      1
George     1
Hannah     1
Dheeraj    1
Name: count, dtype: int64

In [ ]:
df.Department.value_counts()

Department
IT         4
HR         3
Finance    2
Name: count, dtype: int64

In [ ]:
df[df["Department"] == "IT"]["Department"].value_counts()

Department
IT    4
Name: count, dtype: int64

In [ ]:
df[df["Department"] == "IT"]["Bonus"].value_counts()

Bonus
37500.0    1
47500.0    1
36000.0    1
0.0        1
Name: count, dtype: int64

In [ ]:
df

,Employee_ID,Name,Department,Age,Salary,Remote,Extra_Pay,Bonus,DOJ_formatted,NULL
0,101,Alice,IT,28,0,True,0,37500.0,13-10-2026,None
1,102,Bob,HR,34,62000,False,1000,31000.0,14-10-2026,None
2,103,Charlie,IT,41,95000,True,2000,47500.0,15-10-2026,None
3,104,Diana,Finance,29,81000,False,3000,40500.0,16-10-2026,None
4,105,Ethan,HR,36,58000,False,4000,29000.0,17-10-2026,None
5,106,Fiona,Finance,45,105000,True,5000,52500.0,18-10-2026,None
6,107,George,IT,25,72000,True,6000,36000.0,19-10-2026,None
7,108,Hannah,HR,31,68000,False,7000,34000.0,20-10-2026,None
8,109,Dheeraj,IT,27,90000,False,50000,0.0,21-10-2026,None

In [ ]:
df.groupby(by="Department")["Bonus"].sum()

Department
Finance     93000.0
HR          94000.0
IT         121000.0
Name: Bonus, dtype: float64

In [ ]:
df.groupby(by="DOJ_formatted")["Bonus"].sum()

DOJ_formatted
13-10-2026    37500.0
14-10-2026    31000.0
15-10-2026    47500.0
16-10-2026    40500.0
17-10-2026    29000.0
18-10-2026    52500.0
19-10-2026    36000.0
20-10-2026    34000.0
21-10-2026        0.0
Name: Bonus, dtype: float64

In [ ]:
df.groupby(by="Name")["Bonus"].sum()

Name
Alice      37500.0
Bob        31000.0
Charlie    47500.0
Dheeraj        0.0
Diana      40500.0
Ethan      29000.0
Fiona      52500.0
George     36000.0
Hannah     34000.0
Name: Bonus, dtype: float64

In [ ]:
df

,Employee_ID,Name,Department,Age,Salary,Remote,Extra_Pay,Bonus,DOJ_formatted,NULL
0,101,Alice,IT,28,0,True,0,37500.0,13-10-2026,None
1,102,Bob,HR,34,62000,False,1000,31000.0,14-10-2026,None
2,103,Charlie,IT,41,95000,True,2000,47500.0,15-10-2026,None
3,104,Diana,Finance,29,81000,False,3000,40500.0,16-10-2026,None
4,105,Ethan,HR,36,58000,False,4000,29000.0,17-10-2026,None
5,106,Fiona,Finance,45,105000,True,5000,52500.0,18-10-2026,None
6,107,George,IT,25,72000,True,6000,36000.0,19-10-2026,None
7,108,Hannah,HR,31,68000,False,7000,34000.0,20-10-2026,None
8,109,Dheeraj,IT,27,90000,False,50000,0.0,21-10-2026,None

In [ ]:
df.groupby(by="Department").agg({"Salary": "sum", "Employee_ID": "count"})

            Salary  Employee_ID
Department
Finance     186000            2
HR          188000            3
IT          257000            4

In [ ]:
df[df.Department == "IT"]

,Employee_ID,Name,Department,Age,Salary,Remote,Extra_Pay,Bonus,DOJ_formatted,NULL
0,101,Alice,IT,28,0,True,0,37500.0,13-10-2026,None
2,103,Charlie,IT,41,95000,True,2000,47500.0,15-10-2026,None
6,107,George,IT,25,72000,True,6000,36000.0,19-10-2026,None
8,109,Dheeraj,IT,27,90000,False,50000,0.0,21-10-2026,None

In [ ]:
df[df.Department == "IT"]["Salary"].sum()

np.int64(257000)

In [ ]:
df1 = pd.DataFrame({"ID": [1,2,3,6], "Name": ["A", "B", "C", "G"]})
df1

   ID Name
0   1    A
1   2    B
2   3    C
3   6    G

In [ ]:
df2 = pd.DataFrame({"ID": [1,2,3,4], "Score": [88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   3     77
3   4     79

In [ ]:
pd.concat((df1, df2), axis=1)

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   3     77
3  NaN  NaN   4     79

In [ ]:
pd.merge(left=df1, right=df2, how="left", on="ID")

   ID Name  Score
0   1    A   88.0
1   2    B   96.0
2   3    C   77.0
3   6    G    NaN

In [ ]:
pd.merge(left=df1, right=df2, how="right", on="ID")

   ID Name  Score
0   1    A     88
1   2    B     96
2   3    C     77
3   4  NaN     79

In [ ]:
pd.merge(left=df1, right=df2, how="outer", on="ID")

   ID Name  Score
0   1    A   88.0
1   2    B   96.0
2   3    C   77.0
3   4  NaN   79.0
4   6    G    NaN

In [ ]:
pd.merge(left=df1, right=df2, how="inner", on="ID")

   ID Name  Score
0   1    A     88
1   2    B     96
2   3    C     77

In [ ]:
pd.merge(left=df1, right=df2, how="inner", left_on="ID", right_on="ID")

   ID Name  Score
0   1    A     88
1   2    B     96
2   3    C     77